// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/_render.ts";
import * as $1 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/_render.ts": $0,
    "./routes/index.tsx": $1,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
